[[trainers]]
name = 'test'
sprite = 'yo'
id = 'cb44adb8-a0bb-4bfb-af26-300fd86f4f87'
classType = 'elite4'

[[trainers.pokemon]]
species = 'Blastoise'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1

[[trainers.pokemon]]
species = 'Camrupt'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1

[[trainers.pokemon]]
species = 'Blastoise'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1

[[trainers.pokemon]]
species = 'Camrupt'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1

[[trainers.pokemon]]
species = 'Camrupt'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1

[[trainers.pokemon]]
species = 'Blastoise'
level = 1
moves = ['bubbles', 'bubbles', 'bubbles', 'bubbles']
heldItem = 'Oran Berry'
hp = 1
attack = 1
defense = 1
speed = 1
specialAttack = 1
specialDefense = 1
